### PR TITLE
Create yellowpages.html

### PR DESCRIPTION
**Pull request by albjeremias**

### CODE REVIEW

**Comment by albjeremias** [comment]
yellow pages would be available in:
https://guru3.eventphone.de/satic/yellowpages.html

**Comment by sur5r** [comment]
What's the improvement over https://guru3.eventphone.de/event/gelbeseiten?

**Comment by albjeremias** [comment]
the phonebooth is broken and this is a fix.. so that you use clicks to go to[ next page and previous page](https://github.com/eventphone/guru3/pull/28/files#diff-0721ff0081d33df159743465c8d2c7416ea4caf0ec3e677e383a5815f63ce8c0R175).
instead of trying to render almost 7000 phone numbers, it [loads ?n= by n ! :)
](https://github.com/eventphone/guru3/pull/28/files#diff-0721ff0081d33df159743465c8d2c7416ea4caf0ec3e677e383a5815f63ce8c0R85)

**Comment by albjeremias** [comment]
if you can please deploy it.. we can use this address in the phoneboot i think.. might be buggy.. jeje i tried on localhost, and had to change some routes for this PR

**Comment by garw** [comment]
This project prefers to provide public services without javascript and wants to preserve user privacy and thus does not include components from 3rd party CDNs. 
As far as I can see you can host this page anywhere in the web if you want to use it for your own purposes.
On a normal PC the yellow pages render just fine - even on lower compute power PC.

**Pull request closed without merging**
